---
- name: create group
  hosts: db
  tasks:
  - name: using group module
    group:
      name: awx_test
      state: present
      gid: 2100

  - name: using user module
    ansible.builtin.user:
      name: awx_test
      uid: 2100
      group: awx_test
